create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.topics(id) on delete restrict,
  title text not null,
  content jsonb not null,
  question_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quizzes_topic_id_idx on public.quizzes(topic_id);

-- The V1 app uses the server-side service role key for admin CRUD.
-- Keep RLS enabled and never expose the service-role key to the browser.
alter table public.topics enable row level security;
alter table public.quizzes enable row level security;

-- No anon/authenticated policies are created in this V1 because there is no
-- authentication yet. The server-side service role bypasses RLS.
